### ISSUE TITLE
Can you remove/overwrite rituals with this?

### ISSUE THREAD

**Issue by CrowOfDionysia** [InfernalCoding/EidolonDataRecipesComplete-Master#1]
I'm very new to writing data packs so assume I know nothing.

I've noticed you can call back to pages in the codex with this. Is there a way to completely overwrite the recipe of an existing recipe all together?

**Comment by InfernalCoding** [comment]
Yes, you just need to refer to the correct recipe id in the file name and it'll completely override it.
