### ISSUE TITLE
Eidolon Rebrewed Data Recipes - Version check failure?

### ISSUE THREAD

**Issue by Stro-Berry** [InfernalCoding/EidolonDataRecipesComplete-Master#2]
I have a modpack with Eidolon Rebrewed + data recipes, and when i try to launch it it says that the eidolon version is incorrect, despite the correct version being installed
![image](https://github.com/user-attachments/assets/de2070f3-ba8c-4594-9c25-f1b249156a19)
![image](https://github.com/user-attachments/assets/8b2e0d04-173b-4967-8fdd-c25c89421e60)

**Comment by InfernalCoding** [comment]
Problem fixed.
