### ISSUE TITLE
Eidolon Data Recipes Rebrewed - Causing [INTERNAL SERVER ERROR] when trying to join a server with recipes from it

### ISSUE THREAD

**Issue by Stro-Berry** [InfernalCoding/EidolonDataRecipesComplete-Master#3]
I've made a few recipes with the mod and added it to a server. When I tested the recipes in singleplayer they worked correctly, but when I tried to join a server with the recipes on it, I am unable to join because of an "Internal Server Error." The error is caused by this mod as stated in logs.

![image](https://github.com/user-attachments/assets/58e2f341-c6b2-4f49-920c-792ffeb94118)
[log.txt](https://github.com/user-attachments/files/16575474/log.txt)

If this mod doesn't support server functionality then I request that it is updated to support it. I am making a modpack that needs custom eidolon recipes to function and would like to run a server with it.

**Comment by Stro-Berry** [comment]
If this is impossible to do within a reasonable timeframe please let me know ASAP so I can enact a backup plan on the modpack, thank you!

**Comment by InfernalCoding** [comment]
Problem resolved.

**Comment by Stro-Berry** [comment]
Thank you!!! I'll make sure to credit you in the modpack's description
