### ISSUE TITLE
Eidolon Rebrewed Data Recipes - Server crashing on any user join

### ISSUE THREAD

**Issue by Stro-Berry** [InfernalCoding/EidolonDataRecipesComplete-Master#6]
Instead of people being unable to join the server with the mod installed, the entire server crashes instead.

I believe this only happens when actual recipes are added with the mod.

[crash report](https://github.com/user-attachments/files/16590651/crash-2024-08-12_10.44.56-server.txt)

**Comment by InfernalCoding** [comment]
Problem resolved.
